=== tamashiqqe/LABS_OOP2/src/test/resources/xsd/device.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Перелічувані типи -->
    <xs:simpleType name="PeripheralType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="периферійне"/>
            <xs:enumeration value="не_периферійне"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CoolingType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="так"/>
            <xs:enumeration value="ні"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PortType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="COM"/>
            <xs:enumeration value="USB"/>
            <xs:enumeration value="LPT"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Елемент Device -->
    <xs:element name="Device">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Component" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Type">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Peripheral" type="PeripheralType"/>
                                        <xs:element name="EnergyConsumption" type="xs:int"/>
                                        <xs:element name="Cooling" type="CoolingType"/>
                                        <xs:element name="Group" type="xs:string"/>
                                        <xs:element name="Ports">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Port" type="PortType" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="Name" type="xs:string" use="required"/>
                        <xs:attribute name="Origin" type="xs:string" use="required"/>
                        <xs:attribute name="Price" type="xs:decimal" use="required"/>
                        <xs:attribute name="Critical" type="xs:boolean" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== tamashiqqe/LABS_OOP2/src/test/resources/test_device.xml
<?xml version="1.0" encoding="UTF-8"?>
<Device  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/device.xsd">
    <Component Name="Graphics Card" Origin="USA" Price="15000.00" Critical="true">
        <Type>
            <Peripheral>не_периферійне</Peripheral>
            <EnergyConsumption>250</EnergyConsumption>
            <Cooling>так</Cooling>
            <Group>мультимедійні</Group>
            <Ports>
                <Port>USB</Port>
                <Port>COM</Port>
            </Ports>
        </Type>
    </Component>
    <Component Name="Keyboard" Origin="China" Price="1000.00" Critical="false">
        <Type>
            <Peripheral>периферійне</Peripheral>
            <EnergyConsumption>5</EnergyConsumption>
            <Cooling>ні</Cooling>
            <Group>пристрої введення-виведення</Group>
            <Ports>
                <Port>USB</Port>
            </Ports>
        </Type>
    </Component>
</Device>
